# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Bun image
FROM imbios/bun-node:1.1.38-18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and bun.lockb (if it exists)
COPY package.json ./
COPY bun.lock ./

# Copy the rest of the application
COPY . .

# Install dependencies
RUN bun install

# Environment setup
ENV NODE_ENV=production

# Start the server using Bun
ENTRYPOINT ["bun", "run", "./src/index.ts"]
